/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package items;

import client.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import admin.AdminMain;

/**
 *
 * @author Amer Osama
 */
public class ItemsDetails extends javax.swing.JFrame {

    /**
     * Creates new form Cashiers
     */
    public ItemsDetails() {
        initComponents();
        show_item();
        this.setTitle("Items Data");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtcost = new javax.swing.JTextField();
        addclient = new javax.swing.JButton();
        updateclient = new javax.swing.JButton();
        deleteclient = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Itemstable = new javax.swing.JTable();
        searchclient = new javax.swing.JButton();
        name1 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        display = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        phone1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        mysize = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 2));

        jLabel1.setBackground(new java.awt.Color(153, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("تعديل العناصر  ");
        jLabel1.setOpaque(true);

        name.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        name.setForeground(new java.awt.Color(255, 102, 0));
        name.setText("الاسم");

        phone.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        phone.setForeground(new java.awt.Color(255, 102, 0));
        phone.setText("السعر");

        txtname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtnameMouseClicked(evt);
            }
        });
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });

        txtcost.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcost.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        addclient.setBackground(new java.awt.Color(255, 51, 51));
        addclient.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        addclient.setForeground(new java.awt.Color(255, 255, 255));
        addclient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/additem.png"))); // NOI18N
        addclient.setText("اضافه");
        addclient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addclientActionPerformed(evt);
            }
        });

        updateclient.setBackground(new java.awt.Color(255, 51, 51));
        updateclient.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        updateclient.setForeground(new java.awt.Color(255, 255, 255));
        updateclient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.png"))); // NOI18N
        updateclient.setText("تحديث");
        updateclient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateclientActionPerformed(evt);
            }
        });

        deleteclient.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        deleteclient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        deleteclient.setText("حذف");
        deleteclient.setVisible(false);
        deleteclient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteclientActionPerformed(evt);
            }
        });

        Itemstable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Itemstable.setForeground(new java.awt.Color(0, 102, 102));
        Itemstable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "السعر", "الحجم", "اسم الصنف", "id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Itemstable.setGridColor(new java.awt.Color(0, 153, 153));
        Itemstable.setRowHeight(20);
        Itemstable.setRowMargin(3);
        Itemstable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ItemstableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Itemstable);
        if (Itemstable.getColumnModel().getColumnCount() > 0) {
            Itemstable.getColumnModel().getColumn(3).setMinWidth(0);
            Itemstable.getColumnModel().getColumn(3).setMaxWidth(0);
        }

        searchclient.setBackground(new java.awt.Color(255, 51, 51));
        searchclient.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        searchclient.setForeground(new java.awt.Color(255, 255, 255));
        searchclient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        searchclient.setText("بحث");
        searchclient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchclientActionPerformed(evt);
            }
        });

        name1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        name1.setForeground(new java.awt.Color(255, 102, 0));
        name1.setText("id");
        name1.setVisible(false);

        txtid.setEditable(false);
        txtid.setBackground(new java.awt.Color(204, 204, 204));
        txtid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtid.setVisible(false);
        txtid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });

        display.setBackground(new java.awt.Color(255, 51, 51));
        display.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        display.setForeground(new java.awt.Color(255, 255, 255));
        display.setText("عرض الكل");
        //display.setVisible(false);
        display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayActionPerformed(evt);
            }
        });

        exit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exit.setForeground(new java.awt.Color(0, 0, 102));
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        exit.setBorder(null);
        exit.setContentAreaFilled(false);
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        phone1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        phone1.setForeground(new java.awt.Color(255, 102, 0));
        phone1.setText("الحجم");

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new.png"))); // NOI18N
        jButton1.setText("تنظيف");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        mysize.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mysize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "كبير", "وسط", "صغير", " " }));
        mysize.setSelectedIndex(3);
        mysize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mysizeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(563, 563, 563)
                        .addComponent(deleteclient))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(searchclient, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addclient)
                        .addGap(18, 18, 18)
                        .addComponent(updateclient)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(50, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtcost, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(mysize, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(phone1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton1)
                                            .addComponent(name1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addComponent(exit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(exit)
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phone1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mysize, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(79, 79, 79)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchclient, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addclient)
                            .addComponent(updateclient))))
                .addGap(28, 28, 28)
                .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(deleteclient)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //for searching about a person in clients table
    
    private void searchclientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchclientActionPerformed
        // TODO add your handling code here:
       

       find_item();
           
       
        
    }//GEN-LAST:event_searchclientActionPerformed

         public void find_item()
        {
            ArrayList<Items>clients= ListItems(txtname.getText());
            if (clients.isEmpty())
                JOptionPane.showMessageDialog(null, "لا يوجد صنف بهذا الاسم");
                else
            {
        DefaultTableModel model=new DefaultTableModel();
          model.setColumnIdentifiers(new Object[]{"السعر","الحجم ","اسم الصنف","id"});
          
        Object[] row=new Object[5];
        for(int i=0;i<clients.size();i++)
        {
            row[0]=clients.get(i).getCost();
            row[1]=clients.get(i).getSize();
            row[2]=clients.get(i).getName();
            row[3]=clients.get(i).getId();   
            model.addRow(row);
        }  
        Itemstable.setModel(model);
            }
        }
        
    
    
    
        public ArrayList<Items>ListItems(String ValToSearch)
    {
       
        ArrayList<Items>itemsList=new ArrayList<Items>();
          Statement st;
        ResultSet rs; 
        try{
        Connection connection= getConnection();   
        st=connection.createStatement();
        String query="SELECT * FROM `Items` WHERE `Item_name`LIKE '%"+ValToSearch+"%'";
         st.executeQuery("SET NAMES 'UTF8'");
         st.executeQuery("SET CHARACTER SET 'UTF8'");    
        rs=st.executeQuery(query);
            Items item;
            while(rs.next())
            {
                item = new Items(rs.getInt("item_id"),rs.getString("item_name"),rs.getString("item_size"),rs.getFloat("item_cost"));
                itemsList.add(item);
            }
            
        }
        catch(Exception e)
        {
         e.printStackTrace();
        }
        return itemsList;
    }
        
        
         
        
       
        
        // show the Row that is selected from client table on the text field
    private void ItemstableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItemstableMouseClicked
        int i=Itemstable.getSelectedRow();       
        TableModel model=Itemstable.getModel();
        txtcost.setText(model.getValueAt(i, 0).toString());
        //txtsize.setText(model.getValueAt(i, 1).toString());
        mysize.setSelectedItem(model.getValueAt(i, 1).toString());
        txtname.setText(model.getValueAt(i, 2).toString());
        txtid.setText(model.getValueAt(i, 3).toString());
        
       
    }//GEN-LAST:event_ItemstableMouseClicked

    private void deleteclientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteclientActionPerformed
        String query="DELETE FROM `Items` WHERE `item_id`="+txtid.getText();
        executeSQlQuery(query,"حذف  ");
    }//GEN-LAST:event_deleteclientActionPerformed

    private void updateclientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateclientActionPerformed
        String query="UPDATE `Items` SET `item_name`='"+txtname.getText()+"',`item_size`='"+mysize.getSelectedItem()+"',`item_cost`='"+txtcost.getText()+"' WHERE `item_id`="+txtid.getText();
        executeSQlQuery(query," تعديل ");
    }//GEN-LAST:event_updateclientActionPerformed

    private void addclientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addclientActionPerformed
//        String query="INSERT INTO `Items`(`item_name`,`item_size`,`item_cost`) VALUES('"+txtname.getText()+"','"+mysize.getSelectedItem()+"','"+txtcost.getText()+"');";
   //     executeSQlQuery(query, "اضافه ");
     JOptionPane.showMessageDialog(null, " لا يمكنك اضافه عناصر فقط المطور يمكنه الاضافه");
   
    }//GEN-LAST:event_addclientActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayActionPerformed
        // TODO add your handling code here:
        Display_All();
         
    }//GEN-LAST:event_displayActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:   
        this.dispose();
        
        AdminMain main =new AdminMain();
        main.setVisible(true);
    }//GEN-LAST:event_exitActionPerformed

    private void txtnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnameMouseClicked
        // TODO add your handling code here:
             
     
    }//GEN-LAST:event_txtnameMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
               txtid.setText("");
               txtname.setText("");
               txtcost.setText("");
               mysize.setSelectedItem("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void mysizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mysizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mysizeActionPerformed

     public Connection getConnection()
    {
        Connection con;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/projecth","root","");
            return con;
        } catch(Exception e)
        {
           return null;
        }
    }
    public ArrayList<Items>getItemList()
    {
        ArrayList<Items>itemList=new ArrayList<Items>();
        Connection connection= getConnection();
        String query="SELECT * FROM `Items`;";
        Statement st;
        ResultSet rs;
        try{
            st=connection.createStatement();
         st.executeQuery("SET NAMES 'UTF8'");
         st.executeQuery("SET CHARACTER SET 'UTF8'");
            rs=st.executeQuery(query);
            Items item;
            while(rs.next())
            {
                item = new Items(rs.getInt("item_id"),rs.getString("item_name"),rs.getString("item_size"),rs.getFloat("item_cost"));
                itemList.add(item);
            }
            
        }
        catch(Exception e)
        {
         e.printStackTrace();
        }
        return itemList;
    }
 // Display data in JTable
    public void show_item()
    {
        
        ArrayList<Items> list=getItemList();
        DefaultTableModel model=(DefaultTableModel)Itemstable.getModel();
        Object[] row=new Object[4];
        for(int i=0;i<list.size();i++)
        {
            row[0]=list.get(i).getCost();
            row[1]=list.get(i).getSize();
            row[2]=list.get(i).getName();
            row[3]=list.get(i).getId();


            model.addRow(row);
        }  
        
    }
    
    public void Display_All()
    {
        
        ArrayList<Items> list=getItemList();
        DefaultTableModel model=new DefaultTableModel();
          model.setColumnIdentifiers(new Object[]{"السعر","الحجم ","اسم الصنف","id"});
          
        Object[] row=new Object[4];
        for(int i=0;i<list.size();i++)
        {

            row[0]=list.get(i).getCost();
            row[1]=list.get(i).getSize();
            row[2]=list.get(i).getName();
            row[3]=list.get(i).getId();


            model.addRow(row);
        }  
                Itemstable.setModel(model);

        
               

       
        
    }
    

    public void executeSQlQuery(String query, String message)
   {
       Connection con = getConnection();
       Statement st;
       try{
           st = con.createStatement();
            st.executeQuery("SET NAMES 'UTF8'");
         st.executeQuery("SET CHARACTER SET 'UTF8'");
           if((st.executeUpdate(query)) == 1)
           {
            
               // refresh jtable data
               DefaultTableModel model = (DefaultTableModel)Itemstable.getModel();
               model.setRowCount(0);
               show_item();
               txtid.setText("");
               txtname.setText("");
               mysize.setSelectedItem(""); 
               txtcost.setText("");  
              JOptionPane.showMessageDialog(null, "تم "+" "+message+"العنصر بنجاح  "+"  ");
           }else{
               JOptionPane.showMessageDialog(null, "لم يتم "+" "+message+"العنصر ");
           }
       }catch(Exception ex){
           ex.printStackTrace();
           JOptionPane.showMessageDialog(null, "حدد ماذا تريد");
       }
   }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItemsDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItemsDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItemsDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItemsDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ItemsDetails().setVisible(true);
            }
        });
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Itemstable;
    private javax.swing.JButton addclient;
    private javax.swing.JButton deleteclient;
    private javax.swing.JButton display;
    private javax.swing.JButton exit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> mysize;
    private javax.swing.JLabel name;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel phone;
    private javax.swing.JLabel phone1;
    private javax.swing.JButton searchclient;
    private javax.swing.JTextField txtcost;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtname;
    private javax.swing.JButton updateclient;
    // End of variables declaration//GEN-END:variables
}
