/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import cashier.CashMain;
import java.awt.Color;
import java.awt.Font;
import java.io.UnsupportedEncodingException;
import java.sql.SQLIntegrityConstraintViolationException;
import javax.swing.JLabel;

/*
 *
 * @author Amer Osama
 */
public class ClientsDetails extends javax.swing.JFrame {

    /**
     * Creates new form Cashiers
     */
    public ClientsDetails() {
        initComponents();
        show_client();
        this.setTitle("Cashiers Data");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        Address = new javax.swing.JLabel();
        notes = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtphone = new javax.swing.JTextField();
        txtaddress = new javax.swing.JTextField();
        addclient = new javax.swing.JButton();
        updateclient = new javax.swing.JButton();
        deleteclient = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Clientstable = new javax.swing.JTable();
        searchclient = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtnotes = new javax.swing.JTextArea();
        name1 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        display = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 14, 6), 2, true));

        jLabel1.setBackground(new java.awt.Color(153, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("بيانات العملاء  ");
        jLabel1.setOpaque(true);

        name.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        name.setForeground(new java.awt.Color(255, 0, 102));
        name.setText("الاسم");

        phone.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        phone.setForeground(new java.awt.Color(255, 0, 102));
        phone.setText("الهاتف");

        Address.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Address.setForeground(new java.awt.Color(255, 0, 102));
        Address.setText("العنوان");

        notes.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        notes.setForeground(new java.awt.Color(255, 0, 102));
        notes.setText("ملاحظات");

        txtname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtnameMouseClicked(evt);
            }
        });
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });

        txtphone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtphone.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtaddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtaddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        addclient.setBackground(new java.awt.Color(153, 153, 255));
        addclient.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        addclient.setForeground(new java.awt.Color(0, 0, 51));
        addclient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        addclient.setText("اضافه");
        addclient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addclientActionPerformed(evt);
            }
        });

        updateclient.setBackground(new java.awt.Color(153, 153, 255));
        updateclient.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        updateclient.setForeground(new java.awt.Color(0, 0, 51));
        updateclient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.png"))); // NOI18N
        updateclient.setText("تحديث");
        updateclient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateclientActionPerformed(evt);
            }
        });

        deleteclient.setBackground(new java.awt.Color(153, 153, 255));
        deleteclient.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        deleteclient.setForeground(new java.awt.Color(0, 0, 51));
        deleteclient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        deleteclient.setText("حذف");
        deleteclient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteclientActionPerformed(evt);
            }
        });

        Clientstable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Clientstable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "الاسم", "الهاتف", "العنوان", "ملاحظات"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Clientstable.setGridColor(new java.awt.Color(0, 153, 153));
        Clientstable.setRowHeight(20);
        Clientstable.setRowMargin(3);
        Clientstable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClientstableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Clientstable);
        if (Clientstable.getColumnModel().getColumnCount() > 0) {
            Clientstable.getColumnModel().getColumn(0).setMinWidth(0);
            Clientstable.getColumnModel().getColumn(0).setMaxWidth(0);
            Clientstable.getColumnModel().getColumn(1).setPreferredWidth(12);
        }

        searchclient.setBackground(new java.awt.Color(153, 153, 255));
        searchclient.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        searchclient.setForeground(new java.awt.Color(0, 0, 51));
        searchclient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        searchclient.setText("بحث");
        searchclient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchclientActionPerformed(evt);
            }
        });

        txtnotes.setColumns(20);
        txtnotes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnotes.setRows(5);
        jScrollPane2.setViewportView(txtnotes);

        name1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        name1.setForeground(new java.awt.Color(255, 0, 102));
        name1.setVisible(false);
        name1.setText("id");

        txtid.setEditable(false);
        txtid.setBackground(new java.awt.Color(204, 204, 204));
        txtid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtid.setVisible(false);
        txtid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });

        display.setBackground(new java.awt.Color(153, 153, 255));
        display.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        display.setForeground(new java.awt.Color(0, 0, 51));
        display.setText("عرض الكل");
        display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayActionPerformed(evt);
            }
        });

        exit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exit.setForeground(new java.awt.Color(0, 0, 102));
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        exit.setBorder(null);
        exit.setContentAreaFilled(false);
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 51));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new.png"))); // NOI18N
        jButton1.setText("تنظيف");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 45, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtphone)
                                        .addComponent(txtaddress)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(notes, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(name1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(6, 6, 6)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(searchclient, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(addclient)
                                        .addGap(18, 18, 18)
                                        .addComponent(updateclient))
                                    .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(deleteclient)))))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(notes, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchclient, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addclient)
                            .addComponent(updateclient)
                            .addComponent(deleteclient))
                        .addGap(37, 37, 37)
                        .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(exit)
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //for searching about a person in clients table
    
    private void searchclientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchclientActionPerformed
        // TODO add your handling code here:
       

       find_client();
           
       
        
    }//GEN-LAST:event_searchclientActionPerformed

         public void find_client()
        {
            ArrayList<Client>clients= ListClients(txtname.getText());
            if (clients.isEmpty())
                JOptionPane.showMessageDialog(null, "لا يوجد مستخدم بهذا الاسم");
                else
            {
        DefaultTableModel model=new DefaultTableModel();
          model.setColumnIdentifiers(new Object[]{"id","الاسم ","الهاتف","العنوان","ملاحظات"});
        Object[] row=new Object[5];
        for(int i=0;i<clients.size();i++)
        {
            row[0]=clients.get(i).getid();
            row[1]=clients.get(i).getName();
            row[2]=clients.get(i).getPhone();
            row[3]=clients.get(i).getAddress();
            row[4]=clients.get(i).getNotes();

            
            model.addRow(row);
        }  
        Clientstable.setModel(model);
                    }
        }
        
    
    
    
        public ArrayList<Client>ListClients(String ValToSearch)
    {
       
        ArrayList<Client>clientsList=new ArrayList<Client>();
          Statement st;
        ResultSet rs;
        try{
        Connection connection= getConnection();   
        st=connection.createStatement();
//         st.executeQuery("SET NAMES 'UTF8'");
//         st.executeQuery("SET CHARACTER SET 'UTF8'");
        String query="SELECT * FROM `clients` WHERE `client_name`LIKE '%"+ValToSearch+"%'";
            rs=st.executeQuery(query);
            Client client;
            while(rs.next())
            {
                client = new Client(rs.getInt("client_id"),rs.getString("client_name"),rs.getString("client_phone"),rs.getString("client_address"),rs.getString("client_notes"));
               clientsList.add(client);
            }
            
        }
        catch(Exception e)
        {
         e.printStackTrace();
        }
        return clientsList;
    }
        
        
         
        
       
        
        // show the Row that is selected from client table on the text field
    private void ClientstableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClientstableMouseClicked
        int i=Clientstable.getSelectedRow();       
        TableModel model=Clientstable.getModel();
        txtid.setText(model.getValueAt(i, 0).toString());
        txtname.setText(model.getValueAt(i, 1).toString());
        txtphone.setText(model.getValueAt(i, 2).toString());
        txtaddress.setText(model.getValueAt(i, 3).toString());
        txtnotes.setText(model.getValueAt(i, 4).toString());
       
    }//GEN-LAST:event_ClientstableMouseClicked

    private void deleteclientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteclientActionPerformed
        String query="DELETE FROM `clients` WHERE `client_id`="+txtid.getText();
        executeSQlQuery(query,"حذف  ");
    }//GEN-LAST:event_deleteclientActionPerformed

    private void updateclientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateclientActionPerformed
        String query="UPDATE `Clients` SET `Client_name`='"+txtname.getText()+"',`Client_phone`='"+txtphone.getText()+"',`Client_address`='"+txtaddress.getText()+"',`Client_notes`='"+txtnotes.getText()+"' WHERE `Client_id`="+txtid.getText();
        executeSQlQuery(query,"تعديل  ");
    }//GEN-LAST:event_updateclientActionPerformed

    private void addclientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addclientActionPerformed
     
            String query="INSERT INTO `Clients`(`Client_name`,`Client_phone`,`Client_address`,`Client_notes`) VALUES('"+ txtname.getText() +"','"+ txtphone.getText()+"','"+txtaddress.getText()+"','"+txtnotes.getText()+"');";     
            executeSQlQuery(query, "اضافة  ");
    }//GEN-LAST:event_addclientActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayActionPerformed
        // TODO add your handling code here:
        Display_All();
         
    }//GEN-LAST:event_displayActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
            this.dispose();
        CashMain main =new CashMain();
        main.setVisible(true);
    }//GEN-LAST:event_exitActionPerformed

    private void txtnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnameMouseClicked
        // TODO add your handling code here:
               
    }//GEN-LAST:event_txtnameMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
               txtid.setText("");
               txtname.setText("");
               txtphone.setText("");
               txtaddress.setText("");
               txtnotes.setText("");      
    }//GEN-LAST:event_jButton1ActionPerformed

     public Connection getConnection()
    {
        Connection con;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/projecth","root","");
            return con;
        } catch(Exception e)
        {
           return null;
        }
    }
    public ArrayList<Client>getClientList()
    {
        ArrayList<Client>clientList=new ArrayList<Client>();
        Connection connection= getConnection();
        
        String query="SELECT * FROM `Clients`;";
        Statement st;
        ResultSet rs;
        try{
            st=connection.createStatement();
//             st.executeQuery("SET NAMES 'UTF8'");
//         st.executeQuery("SET CHARACTER SET 'UTF8'");
            rs=st.executeQuery(query);
            Client client;
            while(rs.next())
            {
                client = new Client(rs.getInt("client_id"),rs.getString("client_name"),rs.getString("client_phone"),rs.getString("client_address"),rs.getString("client_notes"));
               clientList.add(client);
            }
            
        }
        catch(Exception e)
        {
         e.printStackTrace();
        }
        return clientList;
    }
 // Display data in JTable
    public void show_client()
    {
        
        ArrayList<Client> list=getClientList();
        DefaultTableModel model=(DefaultTableModel)Clientstable.getModel();
        Object[] row=new Object[5];
        for(int i=0;i<list.size();i++)
        {
            row[0]=list.get(i).getid();
            row[1]=list.get(i).getName();
            row[2]=list.get(i).getPhone();
            row[3]=list.get(i).getAddress();
            row[4]=list.get(i).getNotes();

            
            model.addRow(row);
        }  
        
    }
    
    public void Display_All()
    {
       
        
            ArrayList<Client> list=getClientList();
        DefaultTableModel model=new DefaultTableModel();
          model.setColumnIdentifiers(new Object[]{"id","الاسم ","الهاتف","العنوان","ملاخظات"});
        Object[] row=new Object[5];
        for(int i=0;i<list.size();i++)
        {
            row[0]=list.get(i).getid();
            row[1]=list.get(i).getName();
            row[2]=list.get(i).getPhone();
            row[3]=list.get(i).getAddress();
            row[4]=list.get(i).getNotes();

            
            model.addRow(row);
        }
        
               Clientstable.setModel(model);

       
        
    }
    
    
 
    
    
    
    
    public void executeSQlQuery(String query, String message)
   {
       Connection con = getConnection();
       Statement st;
       try{
           st = con.createStatement();
//            st.executeQuery("SET NAMES 'UTF8'");
//         st.executeQuery("SET CHARACTER SET 'UTF8'");
           if((st.executeUpdate(query)) == 1)
           {
               // refresh jtable data
               DefaultTableModel model = (DefaultTableModel)Clientstable.getModel();
               model.setRowCount(0);
               show_client();
               txtid.setText("");
               txtname.setText("");
               txtphone.setText("");
               txtaddress.setText("");
               txtnotes.setText("");               
               JOptionPane.showMessageDialog(null, "تم "+message+"العميل بنجاح  "+"  ");
           }else{
               JOptionPane.showMessageDialog(null, "لم يتم "+message+"العميل ");
           }
       }
       catch(SQLIntegrityConstraintViolationException  ex){
           JLabel label = new JLabel("تم طلب اوردرات من قبل هذا العميل من قبل لا يمكن حذفه");
           label.setFont(new Font("Arial", Font.BOLD, 14));
           if(message.equals("حذف  "))
               JOptionPane.showMessageDialog(null, label,"ERROR",JOptionPane.WARNING_MESSAGE);
           
       }
       catch(Exception ex)
       {
          
             System.out.print(ex.toString());
               JOptionPane.showMessageDialog(null, "حدد ماذا تريد");
       }
   }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientsDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientsDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientsDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientsDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientsDetails().setVisible(true);
            }
        });
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address;
    private javax.swing.JTable Clientstable;
    private javax.swing.JButton addclient;
    private javax.swing.JButton deleteclient;
    private javax.swing.JButton display;
    private javax.swing.JButton exit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel name;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel notes;
    private javax.swing.JLabel phone;
    private javax.swing.JButton searchclient;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextArea txtnotes;
    private javax.swing.JTextField txtphone;
    private javax.swing.JButton updateclient;
    // End of variables declaration//GEN-END:variables
}
